# Generated by Django 3.2.13 on 2022-06-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingridients',
            field=models.TextField(default='ingridients list goes here'),
            preserve_default=False,
        ),
    ]
