# Generated by Django 3.2.13 on 2022-06-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addrecipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecipe',
            name='created_by',
        ),
    ]
