# Generated by Django 3.2.13 on 2022-06-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addrecipe', '0002_remove_userrecipe_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecipe',
            name='user',
        ),
    ]
