# Generated by Django 3.2.13 on 2022-06-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addrecipe', '0004_userrecipe_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecipe',
            name='added_by',
        ),
    ]
