# Generated by Django 3.2.13 on 2022-06-19 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addrecipe', '0005_remove_userrecipe_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecipe',
            old_name='recipe_title',
            new_name='recipe_slug',
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='added_by',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, related_name='user_recipe_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
