# Generated by Django 3.2.13 on 2022-06-19 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addrecipe', '0006_auto_20220619_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecipe',
            name='added_by',
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='added_by_user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='user_recipe_list', to='auth.user'),
            preserve_default=False,
        ),
    ]
