# Generated by Django 3.2.13 on 2022-06-19 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addrecipe', '0007_auto_20220619_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecipe',
            name='added_by_user',
        ),
    ]
