# Generated by Django 3.2.13 on 2022-06-22 18:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recepte'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepte',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
