# Generated by Django 3.2.13 on 2022-06-23 07:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepte',
            name='directions',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
