# Generated by Django 3.2.13 on 2022-06-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_delete_recepte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='excerpt',
        ),
    ]
